### ISSUE TITLE
inject credentials or ssh keys

### ISSUE THREAD

**Issue by jperrin** [mndar/rbf#2]
It would be nice to be able to set a root password (or inject an ssh key) so that no console access is necessary.

**Comment by mndar** [comment]
Thanks for the suggestion. I had included adding a root password in my GSoC proposal and was going to do it after the mid term evaluation. Had not thought about ssh key. Will definitely implement it.

**Comment by mndar** [comment]
Already implemented long time back. Had not closed the issue.
