### ISSUE TITLE
RBF on Python 2.6

### ISSUE THREAD

**Issue by arnebjarne** [mndar/rbf#3]
I'm running on Redsleeve OS (armv5l)

I made the following patch for making it run on non-Python 2.7:

--- cut ---
--- rbf.py.org  2015-10-18 14:21:07.445740342 +0000
+++ rbf.py      2015-10-18 14:34:29.273331152 +0000
@@ -218,7 +218,7 @@
             self.workDir = self.getTagValue(self.boardDom, "workdir")
             self.finalizeScript = self.getTagValue(self.boardDom,\
                                                    "finalizescript")
-            self.loopDevice = subprocess.check_output(['losetup', '-f']).strip()
- ```
         self.loopDevice = subprocess.Popen(['losetup', '-f'], stdout=subprocess.PIPE).communicate()[0].strip()
       self.selinuxConf = self.getTagValue(self.boardDom, "selinux")
       self.etcOverlay = self.getTagValue(self.boardDom, "etcoverlay")
       self.linuxDistro = self.getTagValue(self.boardDom, "distro")
  ```
  
  @@ -1169,7 +1169,7 @@
       logging.error("This script is not meant to be run on " + \
                     platform.uname()[5])
-    if checkCommandExistsAccess(['echo', 'dd', 'parted', 'read', 'losetup', \
-    if checkCommandExistsAccess(['echo', 'dd', 'parted', 'losetup', \
   'mount', 'mkdir', 'rm', 'cat', 'cp', 'rpm', 'sed', 'chroot', \
   'partprobe', 'chpasswd']):
       logging.info("All Commands Found. Continuing")

--- cut ---

**Comment by mndar** [comment]
Will test out these changes on other distributions and then commit it. Sorry for the delay.

**Comment by mndar** [comment]
Thanks for the patch. I tested it with an image generated using CentOS. Works fine.
Apologies for the delay.
