### ISSUE TITLE
bash location

### ISSUE THREAD

**Issue by arnebjarne** [mndar/rbf#4]
On Redsleeve OS bash is not located in "/usr/bin/bash" but in "/bin/bash". rbf.py fails since bash is hardcoded to "/usr/bin/bash". I have changed it to just "bash" and rely on that user environment path is set correctly.

--- cut ---
@@ -1140,7 +1140,7 @@
         self.cleanupScript.write("exit 0\n")
         self.cleanupScript.close()
         if self.action == "build":
-            cleanupRet = subprocess.call(["/usr/bin/bash", "cleanup.sh"])
-            cleanupRet = subprocess.call(["bash", "cleanup.sh"])

@@ -1216,7 +1216,7 @@

```
 if action == "build":
     logging.info("Running RootFS Build Factory script")
```
-        rbfRet = subprocess.call(["/usr/bin/bash", "rbf.sh"])
- ```
     rbfRet = subprocess.call(["bash", "rbf.sh"])
   if rbfRet == 0:
       logging.info("Successfully Executed rbf.sh")
   else:
  ```
  
  @@ -1226,14 +1226,14 @@
  
  ```
   boardParser.createInitramfs()
   boardParser.configureExtLinux()
  ```
-        initramfsRet = subprocess.call(["/usr/bin/bash", "initramfs.sh"])
- ```
     initramfsRet = subprocess.call(["bash", "initramfs.sh"])
   if initramfsRet != 0:
       logging.error(boardParser.RbfScriptErrors[initramfsRet])
       boardParser.cleanUp()
       sys.exit(initramfsRet)
  
   boardParser.callBoardScripts()
  ```
-        boardScriptRet = subprocess.call(["/usr/bin/bash", "boardscript.sh"])
-        boardScriptRet = subprocess.call(["bash", "boardscript.sh"])
       if boardScriptRet != 0:
           logging.error(boardParser.RbfScriptErrors[boardScriptRet])
           boardParser.cleanUp()

--- cut ---

**Comment by mndar** [comment]
Sorry for the late reply. My viva was going on this past month and now we have our semester exams. I'll look into both your suggestions as soon as the exams as over.

**Comment by mndar** [comment]
Implemented.
